### PR TITLE
feat: repository upgrade/standardization

### PR DESCRIPTION
**Pull request by simas232**
### Main improvements in this PR:
feat:
 * added code of conduct, contributions guideline, issue template, pull request template and .gitignore. These files were taken from [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM) and modified according to this repository.
 * now using **kmx** abbreviation instead of **kmar**, based on KEGG Species three letter code
 * moved biomass composition and protein data to ComplementaryData directory
 * implemented the minimal set of complementary scripts required for the model development in this repository. In total, 7 functions from [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM) repository were implemented and modified according to this repository.
 * re-generated the model files by using the aforementioned complementary scripts (assuming `devel` branch)

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/Kluyveromyces_marxianus-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Review by haowang-bioinfo — COMMENTED** [review]
Better rename `increaseVersion` function in a way (e.g. increaseKmxGemVersion) so that it is unique among other GEM-type repos.

**Comment by simas232** [comment]
@Hao-Chalmers, thank you for the useful comments. The names for the main supplementary functions are now specific to this repository. Regarding several of the functions appearing in `missingFields` and `otherChanges`sub-directories, I left the same function names, because these functions are integrated in a way that MATLAB cannot not confuse them with e.g. corresponding functions appearing in [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM).

**Comment by IVANDOMENZAIN** [comment]
I agree with you both, better to avoid confusion with the `yeast-GEM` repo, as there are users who work even with both models for their projects (CHASSY project, for instance).

**Review by IVANDOMENZAIN — APPROVED** [review]
Everything looks good now!

**Review by haowang-bioinfo — COMMENTED** [review]
A comment to CODE_OF_CONDUCT, which probably could be replaced with a URL to this [file](https://www.sysbio.se/code-of-conduct/).

**Comment by simas232** [comment]
@Hao-Chalmers, okay, I will implement this in the following PR. See PR #2.

**Pull request merged**
