### PR TITLE
feat: finalise repo standardization for Kluyveromyces_marxianus-GEM_v1.0.0

### PR DESCRIPTION
**Pull request by simas232**
### Main improvements in this PR:
* The repository was standardized according to the latest changes in SysBio internal policy:
  * feat: renamed the folders and filenames for model files, also applied the corresponding corrections to the MATLAB functions
  * doc: updated `README.md` to reflect the changed names for several supplementary scripts + other small changes
  * fix: fixed an error in `increaseKmxVersion`, it now correctly calls `saveKmxModel`. Also fixed the potential issue when using this function in `master`

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/Kluyveromyces_marxianus-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by simas232** [comment]
Also fixed `CONTRIBUTING.md` according to the changed names for supplementary scripts

**Comment by simas232** [comment]
There is no need to merge this PR now. Instead, let's apply the new standardisation guidelines as soon as they are stable. I will request the reviews again as soon as these changes are applied in this PR.

**Comment by simas232** [comment]
The changes to the repository are now complete. Zenodo badge will be added as soon as the release is published.

**Review by haowang-bioinfo — COMMENTED** [review]
can you specify the basis for changing these folder names?

**Comment by simas232** [comment]
The folder name changes were applied according to **standard-GEM v0.1**. Although this document is not a final version, I find it solid, since it is based on the experiences gained when maintaining the GEM repositories in Chalmers SysBio, like [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM), [Human-GEM](https://github.com/SysBioChalmers/Human-GEM), [Yarrowia_lipolytica_W29-GEM](https://github.com/SysBioChalmers/Yarrowia_lipolytica_W29-GEM). Moreover, the specifications written in standard-GEM v0.1 are clear and easily implementable to this repository.

There are several changes which should be implemented to Kluyveromyces_marxianus-GEM itself (`metFormulas` and several `grRules`), but we shall release v1.0.0 referring to the published GEM iSM996 first.

**Review by haowang-bioinfo — APPROVED** [review]

**Pull request merged**
